version: "3.8"
services:
    mongodb:
        container_name: 'Pro.IO_Mongo'
        image: 'mongo:4.4.18'
        ports:
            - 27017:27017 
        restart: unless-stopped
    user-service:
        container_name: 'Pro.IO'
        environment:
            - SERVER_PORT
            - DB_URI
            - ACCESS_TOKEN_SECRET
            - REFRESH_TOKEN_SECRET
        build:
            context: ./packages/backEnd/userService
        ports:
            - "4000:4000"
        restart: unless-stopped
        depends_on:
            - mongodb
        command: "echo $DB_URI $SERVER_PORT"