version: "3.8"
services:
    mongodb:
        container_name: 'MongoDb'
        image: 'mongo:4.4.18'
        ports:
            - 27017:27017
        volumes: 
            - '${HOME}/data:/data/db'
        restart: unless-stopped
    userservice:
        container_name: 'UserService'
        env_file: .env
        build:
            context: ./packages/backEnd/userService
        ports:
            - "4001:4000"
        restart: unless-stopped
        depends_on:
            - mongodb
        command: "npm run start"
    matchservice:
        container_name: 'MatchService'
        env_file: .env
        build:
            context: ./packages/backEnd/matchService
        ports:
            - "4002:4000"
        restart: unless-stopped
        depends_on:
            - mongodb
        command: "npm run start"
    gameservice:
        container_name: 'GameService'
        env_file: .env
        build:
            context: ./packages/backEnd/gameService
        ports:
            - "4003:4000"
        restart: unless-stopped
        depends_on:
            - mongodb
        command: "npm run start"
    socketservice:
        container_name: 'SocketService'
        env_file: .env
        build:
            context: ./packages/backEnd/socketService
        ports:
            - "4004:4000"
        restart: unless-stopped
        depends_on:
            - userservice
            - matchservice
            - gameservice
        command: "npm run start"
    chatservice:
        container_name: 'ChatService'
        env_file: .env
        build:
            context: ./packages/backEnd/chatService
        ports:
            - "4005:4000"
        restart: unless-stopped
        depends_on:
            - userservice
            - matchservice
            - gameservice
        command: "npm run start"
    nginx:
        container_name: 'nginx'
        build:
            context: ./packages/backEnd/nginx
        volumes:
            - "./packages/backEnd/nginx:/www/data"
        ports:
            - "80:80"
        restart: unless-stopped
        depends_on:
            - userservice
            - matchservice
            - gameservice
            - socketservice