name: Deploy to Raspberry Pi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a docker image
        run: docker-compose build
          #  docker build -t rpi-cd-tutorial:${{ steps.set_tag_name.outputs.tag_name }} .
  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Kill all running containers
        run: docker-compose down

      - name: Run the docker image
        run: docker-compose up -d
